# 服务端口号
server:
  port: 8003
spring:
  application:
    name: microservice-order # 对外暴露的服务名称

# 数据库地址
#datasource:
#  url: localhost:3306/microservice03

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/microservice03?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root

# 客户端注册进eureka服务列表里
eureka:
  client:
    service-url:
      defaultZone: http://eureka01:7001/eureka/,http://eureka02:7002/eureka/,http://eureka03:7003/eureka/
  instance:
    instance-id: 订单服务-8003 #人性化显示出服务的信息
    prefer-ip-address: true   #访问路径可显示Ip地址

mybatis:
  # 指定别名设置的包为所有entity
  type-aliases-package: com.itcodai.springcloud.entity
  mapper-locations: # mapper映射文件位置
    - classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范

# 用来展示项目的基本信息(在eureka显示页面中点击地址时显示的信息)
info:
  author.name: sy
  app.name: microservice
  server.port: ${server.port}
  application.name: ${spring.application.name}



